backend:
  name: git-gateway
  branch: master

media_folder: "public/media"
public_folder: "/media"

collections:
  - label: "Sections"
    extension: md
    name: "sections"
    folder: "site/sections"
    widget: list
    fields:
      - label: "Body"
        name: "body"
        widget: "markdown"
