backend:
  name: git-gateway
  branch: master

media_folder: "public/media"
public_folder: "/media"

collections:
  - label: "Sections"
    name: "sections"
    folder: "site/sections"
    extension: "md"
    slug: "{{title}}"
    create: true
    fields:
      - label: "File"
        name: "file"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
