backend:
  name: git-gateway
  branch: master

media_folder: "public/media"
public_folder: "/media"

collections:
  - label: "Sections"
    extension: json
    name: "sections"
    files:
      - label: "Background"
        name: "background"
        file: "site/content/background.json"
        fields:
          - label: Content
            name: content
            widget: markdown
      - label: "Selected Publications"
        extension: json
        name: "selected-publications"
        file: "site/content/selected-publications.json"
        fields:
          - label: "Content"
            name: content
            widget: markdown
      - label: "Current Projects"
        extension: md
        name: "current-projects"
        file: "site/content/current-projects.md"
        fields:
          - label: "Content"
            name: "content"
            widget: "markdown"
  - label: "Resources"
    extension: json
    name: "resources"
    folder: "site/content/resources"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            hint: "Title will not be displayed on the page"
            required: true
          - label: "Link"
            name: "link"
            required: false
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
                required: false
              - label: "URL"
                name: "url"
                widget: "string"
                required: true
          - label: "Download Link"
            name: "download-link"
            required: false
            widget: "object"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
                required: false
              - label: "File"
                name: "file"
                widget: "file"
                required: false
          - label: "Content"
            name: "content"
            widget: "markdown"
