backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/uploads"

collections:
  - label: "Sections"
    extension: json
    name: "sections"
    files:
      - label: "Background"
        name: "background"
        file: "site/content/background.json"
        fields:
          - label: Content
            name: content
            widget: markdown
  - label: "Current Projects"
    extension: json
    name: "current-projects"
    folder: "site/content/current-projects"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "markdown"
        required: false
      - label: "Use bullet points"
        name: "bullet"
        widget: "boolean"
        default: false
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false
          - label: "Content"
            name: "content"
            widget: "markdown"
