#!/usr/bin/env bash

set -eu

export AWS_ACCESS_KEY_ID="$(aws configure get personal.aws_access_key_id)"
export AWS_SECRET_ACCESS_KEY="$(aws configure get personal.aws_secret_access_key)"
export AWS_PROFILE="personal"

terraform plan
terraform apply
